pipeline:
  name: NodeJS Hello World CI
  identifier: nodejs_hello_world_ci
  projectIdentifier: Harness101Integration
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Krishnamurtyp_Harness101
        repoName: Krishnamurtyp/Harness-101
        build: main  # Fixed branch or use <+input> for runtime input
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  type: Run
                  name: Start App
                  identifier: start_app
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: |
                      npm start & sleep 5
          infrastructure:
            type: Hosted  # Or 'Docker', 'KubernetesDirect', or 'VM' based on your setup
            spec:
              platform:
                os: Linux
                arch: Amd64
