pipeline:
  name: NodeJS Hello World CI
  identifier: nodejs_hello_world_ci
  projectIdentifier: Harness_101_Integration  # Replace with actual project ID if different
  orgIdentifier: default                      # Replace with actual org ID if not 'default'
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Krishnamurtyp_Harness101  # Ensure this connector exists
        repoName: Krishnamurtyp/Harness-101            # Matches your GitHub repo
        build: <+codebase.branch>                      # Dynamic branch (e.g., 'main')
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  type: Run
                  name: Start App
                  identifier: start_app
                  spec:
                    shell: Sh
                    command: |
                      npm start & sleep 5  # Runs app in background, waits 5s
          infrastructure:
            type: Cloud
            spec: {}
