pipeline:
  name: NodeJS Hello World CI
  identifier: nodejs_hello_world_ci
  projectIdentifier: Harness101Integration
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: GitHub_Krishnamurtyp_Harness101
        repoName: Krishnamurtyp/Harness-101
        build: main  # Hardcoded branch; use <+input> for runtime input if needed
  stages:
    - stage:
        name: Build and Test
        identifier: build_and_test
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  type: Run
                  name: Start App
                  identifier: start_app
                  timeout: 10m
                  spec:
                    shell: Sh
                    command: |
                      npm start & sleep 5
          infrastructure:
            type: KubernetesDirect  # Or 'VM' or 'UseFromStage' based on your setup
            spec:
              connectorRef: your_kubernetes_connector_name  # Replace with actual value
              namespace: your_namespace  # Replace with actual value (e.g., 'default')
              platform:
                os: Linux
                arch: Amd64
