pipeline:
  name: NodeJS CI Pipeline
  identifier: nodejs_ci_pipeline
  projectIdentifier: my_project
  orgIdentifier: my_org
  properties:
    ci:
      codebase:
        connectorRef: my_github_connector
        repoName: harness-ci-example-nodejs
        build: <+codebase.branch>
  stages:
    - stage:
        name: Build and Test
        identifier: build_test
        type: CI
        spec:
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: install_dependencies
                  spec:
                    shell: Sh
                    command: |
                      npm install
              - step:
                  type: Run
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    shell: Sh
                    command: |
                      npm test
              - step:
                  type: Run
                  name: Build Docker Image
                  identifier: build_docker_image
                  spec:
                    shell: Sh
                    command: |
                      eval $(minikube -p minikube docker-env)
                      docker build -t my-nodejs-app:latest .
              - step:
                  type: Run
                  name: Deploy to Minikube
                  identifier: deploy_minikube
                  spec:
                    shell: Sh
                    command: |
                      kubectl apply -f k8s/deployment.yaml
                      kubectl get pods -n default
  infrastructure:
    type: KubernetesDirect
    spec:
      connectorRef: my_minikube_connector
      namespace: default
      cluster: minikube
